config/routes.rb
Rails.application.routes.draw do
  get "meals/index"
  get "less_than5_ingredients/index"
  get "less_than30_mins/index"
  get "desserts/index"
  get "snacks/index"
  get "breakfasts/index"
  get "meal_planner/index"
  resources :tags
  resources :steps
  resources :ingredients
  get "search", to: "search#index"
  devise_for :users
  resources :recipes
  #get "home/index"
  get 'home/about'
  root 'home#index'
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "/recipes/:id", to: "recipes#show"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    
    has_many :ingredients, dependent: :destroy, inverse_of: :recipe
    accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank

    has_many :steps, dependent: :destroy
    accepts_nested_attributes_for :steps, reject_if: :all_blank, allow_destroy: true

    has_many :tags, dependent: :destroy
    accepts_nested_attributes_for :tags, reject_if: :all_blank, allow_destroy: true



    def self.ransackable_attributes(auth_object = nil)
        ["dish_name", "dish_type"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["image_attachment", "image_blob", "user"]
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:show, :edit, :update, :destroy]

  # GET /recipes or /recipes.json
  def index
    @recipes = current_user.recipes
    @q = @recipes.ransack(params[:q])
    @recipes = @q.result(distinct: true)
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find(params[:id])
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.build
    @recipe.ingredients.build
    @recipe.steps.build
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes or /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: "Recipe was successfully created." }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: "Recipe was successfully updated." }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy!

    respond_to do |format|
      format.html { redirect_to recipes_path, status: :see_other, notice: "Recipe was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @recipe = current_user.recipes.find_by(id: params[:id])
    redirect_to recipes_path, notice: "Not Authorized To Edit This Recipe" if @recipe.nil?
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:dish_name, :dish_type, :number_of_likes, :image, :description, :serves, :prep_time, :cook_time, :user_id, ingredients_attributes:[:id, :content, :measurement, :amount, :_destroy], steps_attributes: [:id, :description, :_destroy], tags_attributes: [:id, :value, :_destroy])
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_breakfast_show.html.erb
<% content_for :title, "Recipes" %>

<h1>Recipes</h1>

<% if user_signed_in? %>

<div id="recipes">
<div id="cards"
  <% @recipes.each do |recipe| %>
    <% if recipe.dish_type == "breakfast" %>
        <%= render recipe %>
    <% end %>
  <% end %>
</div>
</div>

<%= link_to "New recipe", new_recipe_path, class:"btn btn-secondary" %>

<% end %>

app/views/recipes/_doit.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Recipe || Final</title>
    <!-- favicon -->
    <link rel="shortcut icon" href="./assets/favicon.ico" type="image/x-icon" />
    <!-- normalize -->
    <link rel="stylesheet" href="./css/normalize.css" />
    <!-- font-awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    />
    <!-- main css -->
    <link rel="stylesheet" href="./css/main.css" />
  </head>
  <body>
    <!-- nav  -->
    <nav class="navbar">
      <div class="nav-center">
        <div class="nav-header">
          <a href="index.html" class="nav-logo">
            <img src="./assets/logo.svg" alt="simply recipes" />
          </a>
          <button class="nav-btn btn">
            <i class="fas fa-align-justify"></i>
          </button>
        </div>
        <div class="nav-links">
          <a href="index.html" class="nav-link"> home </a>
          <a href="about.html" class="nav-link"> about </a>
          <a href="tags.html" class="nav-link"> tags </a>
          <a href="recipes.html" class="nav-link"> recipes </a>

          <div class="nav-link contact-link">
            <a href="contact.html" class="btn"> contact </a>
          </div>
        </div>
      </div>
    </nav>
    <!-- end of nav -->
    <main class="page">
      <div class="recipe-page">
        <section class="recipe-hero">
          <img
            src= <%= @recipe.image %>
            class="img recipe-hero-img"
          />
          <article class="recipe-info">
            <h2><%= @recipe.dish_name %></h2>
            <p>
              Shabby chic humblebrag banh mi bushwick, banjo kale chips
              meggings. Cred selfies sartorial, cloud bread disrupt blue bottle
              seitan. Dreamcatcher tousled bitters, health goth vegan venmo
              whatever street art lyft shabby chic pitchfork beard. Drinking
              vinegar poke tbh, iPhone coloring book polaroid truffaut tousled
              ramps pug trust fund letterpress. Portland four loko austin
              chicharrones bitters single-origin coffee. Leggings letterpress
              occupy pour-over.
            </p>
            <div class="recipe-icons">
              <article>
                <i class="fas fa-clock"></i>
                <h5>prep time</h5>
                <p>30 min.</p>
              </article>
              <article>
                <i class="far fa-clock"></i>
                <h5>cook time</h5>
                <p>15 min.</p>
              </article>
              <article>
                <i class="fas fa-user-friends"></i>
                <h5>serving</h5>
                <p>6 servings</p>
              </article>
            </div>
            <p class="recipe-tags">
              Tags : <a href="tag-template.html">beef</a>
              <a href="tag-template.html">breakfast</a>
              <a href="tag-template.html">pancakes</a>
              <a href="tag-template.html">food</a>
            </p>
          </article>
        </section>
        <!-- content -->
        <section class="recipe-content">
          <article>
            <h4>instructions</h4>
            <!-- single instruction -->
            <div class="single-instruction">
              <header>
                <p>step 1</p>
                <div></div>
              </header>
              <p>
                I'm baby mustache man braid fingerstache small batch venmo
                succulents shoreditch.
              </p>
            </div>
            <!-- end of single instruction -->
            <!-- single instruction -->
            <div class="single-instruction">
              <header>
                <p>step 2</p>
                <div></div>
              </header>
              <p>
                Pabst pitchfork you probably haven't heard of them, asymmetrical
                seitan tousled succulents wolf banh mi man bun bespoke selfies
                freegan ethical hexagon.
              </p>
            </div>
            <!-- end of single instruction -->
            <!-- single instruction -->
            <div class="single-instruction">
              <header>
                <p>step 3</p>
                <div></div>
              </header>
              <p>
                Polaroid iPhone bitters chambray. Cornhole swag kombucha
                live-edge.
              </p>
            </div>
            <!-- end of single instruction -->
          </article>
          <article class="second-column">
            <div>
              <h4>ingredients</h4>
              <p class="single-ingredient">1 1/2 cups dry pancake mix</p>
              <p class="single-ingredient">1/2 cup flax seed meal</p>
              <p class="single-ingredient">1 cup skim milk</p>
            </div>
            <div>
              <h4>tools</h4>
              <p class="single-tool">Hand Blender</p>
              <p class="single-tool">Large Heavy Pot With Lid</p>
              <p class="single-tool">Measuring Spoons</p>
              <p class="single-tool">Measuring Cups</p>
            </div>
          </article>
        </section>
      </div>
    </main>
    <!-- footer -->
    <footer class="page-footer">
      <p>
        &copy; <span id="date"></span>
        <span class="footer-logo">SimplyRecipes</span> Built by
        <a href="https://www.johnsmilga.com/">Coding Addict</a>
      </p>
    </footer>
    <script src="./js/app.js"></script>
  </body>
</html>

app/views/recipes/_form.html.erb
<div class="nav" style="display: flex-inline">
<div>
<%= form_with(model: recipe, data: {
  controller: "nested-form",
  nested_form_wrapper_selector_value: '.nested-form-wrapper'
}) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <form class="d-flex flex-column">
  <!-- First Row -->
  <div class="d-flex nav">
    <div class="form-group mr-4" style="padding-right: 20px;">
      <%= form.label :dish_name, style: "display: block", class:"form-label" %>
      <%= form.text_field :dish_name, class:"form-control", :required => true %>
    </div>
    <div class="form-group mr-4" style="padding-right: 20px;">
      <%= form.label :dish_type, style: "display: block",  class:"form-label" %>
      <%= form.select :dish_type, ['Meal', 'Breakfast', 'Dessert', 'Snack', 'Other']%>
    </div>
  </div>
  </br>
  <!-- Second Row -->
  <div class="d-flex">
    <div class="form-group mr-4 style="padding-right: 20px;">
      <%= form.label :description, style: "display: block;",  class:"form-label" %>
      <%= form.text_area :description, class:"form-control", :required => true, style:"width: 200%;" %>
    </div>
  </div>

  </br>
  <div class="d-flex">
    <div class="form-group mr-4" style="padding-right: 20px;">
      <%= form.label :prep_time, 'How long does it take to prep?', style: "display: block",  class:"form-label" %>
      <%= form.number_field :prep_time, class:"form-control", :required => true %>
    </div>
    <div class="form-group mr-4" style="padding-right: 20px;">
      <%= form.label :cook_time, 'How long does it take to cook?', style: "display: block",  class:"form-label" %>
      <%= form.number_field :cook_time, class:"form-control", :required => true %>
    </div>
    <div class="form-group mr-4" style="padding-right: 20px;">
      <%= form.label :serves, 'How many people does it serve?', style: "display: block",  class:"form-label" %>
      <%= form.number_field :serves, class:"form-control", :required => true %>
    </div>
  </div>

  </br>
  <div class="d-flex">
    <div class="form-group mr-4 style="padding-right: 20px;">
      <%= form.label :image, style: "display: block",  class:"form-label" %>
      <%= form.file_field :image, class:"form-control", :required => true %>
    </div>
  </div>

  </br>
  </br>
  </br>
  </br>

  <h4>Ingredients</h4>
  <div id='ingredients'>
    <%= form.fields_for :ingredients do |ingredient_f| %>
      <%= render 'ingredient_fields', form: ingredient_f %>
    <% end %>
  </div>
  </br>
  <%= link_to_add_nested(form, :ingredients, '#ingredients', link_classes: 'btn btn-primary') %> <!-- adds a link to add more items -->
  </br>
  </br>
  </br>
  </br>
  <h4>Instructions</h4>
  <div id='steps'>
    <%= form.fields_for :steps do |step_f| %>
      <%= render 'step_fields', form: step_f %>
    <% end %>
  </div>
  </br>
  <%= link_to_add_nested(form, :steps, '#steps', link_classes: 'btn btn-primary') %> <!-- adds a link to add more items -->
  </br>
  </br>
  </br>
  </br>
  

  <h4>Tags</h4>
  <div id='tags'>
    <%= form.fields_for :tags do |tag_f| %>
      <%= render 'tag_fields', form: tag_f %>
    <% end %>
  </div>
  </br>
  <%= link_to_add_nested(form, :tags, '#tags', link_classes: 'btn btn-primary') %>

  <div>
    <%= form.submit %>
  </div>
  </form>
<% end %>
</div>
<div>
  <%= image_tag("smoothie_bowl.jpg", class:"img-smaller") %>
</div>
</div>

    

    
    

app/views/recipes/_ingredient_fields.html.erb
<div class="d-flex">
<div class="form-group mr-4" style="padding-right: 20px;">
  <%= form.label :content, "ingredient", class:"form-label" %>
  <%= form.text_field :content, class:"form-control" %>
</div>
<div class="form-group mr-4" style="padding-right: 20px;">
  <%= form.label :amount, "amount", class:"form-label" %>
  <%= form.number_field :amount, class:"form-control", :step => "0.01" %>
</div>
<div class="form-group mr-4" style="padding-right: 20px;">
  <%= form.label :measurement, "measurement", class:"form-label" %>
    <%= form.select :measurement, ['cups', 'tbsp', 'tsp', 'oz', 'g', 'lb', 'ml', 'L', 'None']%>
</div>

<%= link_to_remove_nested(form, link_classes: "btn btn-danger-outline") %>


</div>

app/views/recipes/_ingredient_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
  <%= f.label :content, class:"form-label" %>
  <%= f.text_field :content, class:"form-control" %>

  <%= f.label :amount, class:"form-label" %>
  <%= f.text_field :amount, class:"form-control" %>

  <button type="button" data-action="nested-form#remove" class="btn btn-primary">Remove ingredient</button>

  <%= f.hidden_field :_destroy %>
</div>

app/views/recipes/_recipe.html.erb
<% ref = recipe_path(recipe) %>

<a style="text-decoration:none" href=<%=ref%>>
<div class="recipe-card">
        <figure>
          <%= image_tag(recipe.image)%>
        </figure>
      <div class="card-meta">
      <p class="dish-type-<%= recipe.dish_type%>" style="text-decoration:none" ><%= recipe.dish_type %></p>
      <ul class="dish-stats">
        <li>
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M8 2C4.6875 2 2 4.6875 2 8C2 11.3125 4.6875 14 8 14C11.3125 14 14 11.3125 14 8C14 4.6875 11.3125 2 8 2Z" stroke="#070705" stroke-opacity="0.25" stroke-miterlimit="10"/>
            <path d="M8 4V8.5H11" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
          <% total_time = (recipe.prep_time + recipe.cook_time) %>
            
          <%= total_time %> Mins.
        </li>
        <li>
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M4.9713 2.5C7.00005 2.5 8.00005 4.5 8.00005 4.5C8.00005 4.5 9.00005 2.5 11.0288 2.5C12.6775 2.5 13.9832 3.87937 14 5.52531C14.0344 8.94187 11.2897 11.3716 8.2813 13.4134C8.19836 13.4699 8.10036 13.5 8.00005 13.5C7.89973 13.5 7.80174 13.4699 7.7188 13.4134C4.71067 11.3716 1.96598 8.94187 2.00005 5.52531C2.01692 3.87937 3.32255 2.5 4.9713 2.5Z" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
            
          <%= recipe.number_of_likes %></h1>
        </li>
      </ul>
      </div>
      <h1><%= recipe.dish_name %></h1>
</div>
</a>

app/views/recipes/_recipe_ingredient_form.html.erb
<div class="nested-form-wrapper form-group" data-new-record="<%= f.object.new_record? %>">
  <%= f.label "ingredient" %>
  <%= f.text_field :content, class: "form-control" %>
  <%= f.label :amount %>
  <%= f.text_field :amount, class: "form-control" %>
  <button type="button" data-action="nested-form#remove">Remove ingredient</button>
  <%= f.hidden_field :_destroy %>
</div>

app/views/recipes/_recipe_step_form.html.erb
<div class="nested-fields" style="margin-bottom: 20px;">
  <%= f.label :description, "Step Description" %>
  <%= f.text_area :description, style:"margin-bottom: 20px;" %>

  <!-- Button to remove this step field set -->
  <button type="button" data-action="steps-form#removeField" style="margin-bottom: 20px;">Remove Step</button>
</div>
</br>

app/views/recipes/_step_fields.html.erb
<div class="d-flex">
<div class="form-group mr-4" style="padding-right: 20px;">
  <%= form.text_area :description, class:"form-control" %>
</div>

<%= link_to_remove_nested(form, link_classes: 'btn btn-primary', link_text: "Delete Step") %>

</div>

app/views/recipes/_tag_fields.html.erb
<div class="d-flex">
<div class="form-group mr-4" style="padding-right: 20px;">
  <%= form.text_field :value, class:"form-control" %>
</div>

<%= link_to_remove_nested(form, link_classes: 'btn btn-primary') %>

</div>

app/views/recipes/edit.html.erb
<% content_for :title, "Editing recipe" %>

<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe, class:"btn btn-secondary" %> 
  <%= link_to "Back to recipes", recipes_path, class:"btn btn-dark" %>
</div>

<%= form_with model: @recipe, data: { controller: 'nested-form', nested_form_wrapper_selector_value: '.nested-form-wrapper' } do |f| %>
  <template data-nested-form-target="template">
    <%= f.fields_for :ingredients, Ingredient.new, child_index: 'NEW_RECORD' do |ingredient_fields| %>
      <%= render "ingredient_form", f: ingredient_fields %>
    <% end %>
  </template>

  <%= f.fields_for :ingredients do |ingredient_fields| %>
    <%= render "ingredient_form", f: ingredient_fields %>
  <% end %>

  <!-- Inserted elements will be injected before that target. -->
  <div data-nested-form-target="target"></div>

  <button type="button" data-action="nested-form#add">Add ingredient</button>

  <%= f.submit 'Save ingredients' %>
<% end %>

app/views/recipes/index.html.erb
<% content_for :title, "Recipes" %>
<% if user_signed_in? %>
<% if @recipes.empty? %>
  <h1> No recipes yet </h1>
  <%= link_to "New recipe", new_recipe_path, class:"btn btn-secondary" %>
<% else %>
<h1>Recipes</h1>
<%= link_to "New recipe", new_recipe_path, class:"btn btn-secondary" %>
<div class="recipes">
<div class="cards">
  <% @recipes.each do |recipe| %>
    <%= render recipe %>
  <% end %>
</div>
</div>
<% end %>

<% end %>

app/views/recipes/new.html.erb
<% content_for :title, "New recipe" %>

<h1>New recipe</h1>
</br>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back", recipes_path, class:"btn btn-dark" %>
</div>

app/views/recipes/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Recipe || Final</title>
    <!-- favicon -->
    <link rel="shortcut icon" href="./assets/favicon.ico" type="image/x-icon" />
    <!-- normalize -->
    <link rel="stylesheet" href="./css/normalize.css" />
    <!-- font-awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    />
    <!-- main css -->
    <link rel="stylesheet" href="./css/main.css" />
  </head>
  <body>
    <main class="page">
      <div class="recipe-page">
        <section class="recipe-hero">
          <figure class="show">
            <%= image_tag(@recipe.image, class: "oval")%>
          </figure>
          <article class="recipe-info">
            <h2><%= @recipe.dish_name %></h2>
            <p>
              <%= @recipe.description %>
            </p>
            <div class="recipe-icons recipe-icons-<%=@recipe.dish_type %>">
              <article>
                <i class="fas fa-clock"></i>
                <h5>prep time</h5>
                <p><%= @recipe.prep_time%> min</p>
              </article>
              <article>
                <i class="far fa-clock"></i>
                <h5>cook time</h5>
                <p><%= @recipe.cook_time%> min</p>
              </article>
              <article>
                <i class="fas fa-user-friends"></i>
                <h5>serving</h5>
                <p id="serving-size"><%= @recipe.serves %> servings</p>
              </article>
            </div>
            <p class="recipe-tags-<%=@recipe.dish_type%>">
              Tags : <% @recipe.tags.each do |tag| %>
              <a href="../search?q%5Bdish_name_or_dish_type_i_cont%5D=<%= tag.value %>&commit=Search"><%= tag.value %></a>
              <% end %>
            </p>
            <label for="batch-size">Select Batch Size:</label>
            <select id="batch-size">
              <% (1..5).each do |i| %>
                <option value="<%= i %>"><%= i %></option>
              <% end %>
            </select>
          </article>
        </section>
        <!-- content -->
        <section class="recipe-content">
          <article>
            <h4>instructions</h4>
            <!-- single instruction -->
            <% counter = 1 %>
            <% @recipe.steps.each do |step| %>
            <div class="single-instruction single-instruction-<%=@recipe.dish_type%>">
              <header>
                <p>step <%= counter %></p>
                <div></div>
              </header>
              <p>
                <%= step.description %>
              </p>
              <% counter = counter + 1 %>
            </div>
            <% end %>
            <!-- end of single instruction -->
            <!-- single instruction -->
          </article>
          <article class="second-column">
            <div>
              <h4>ingredients</h4>
              <% @recipe.ingredients.each do |ingredient| %>
                <% if ingredient.measurement != "None" %>
                <p class="single-ingredient" data-amount="<%= ingredient.amount %>">
                  <span class="ingredient-amount"><%= ingredient.amount %></span>
                  <%= ingredient.measurement %> <%= ingredient.content %></p>
                <% else %>
                  <p class="single-ingredient" data-amount="<%= ingredient.amount %>">
                  <span class="ingredient-amount"><%= ingredient.amount %></span>
                  <%= ingredient.content %></p>
                <% end %>          
              <% end %>
            </div>
            <div>
              <h4>tools</h4>
              <p class="single-tool">Hand Blender</p>
              <p class="single-tool">Large Heavy Pot With Lid</p>
              <p class="single-tool">Measuring Spoons</p>
              <p class="single-tool">Measuring Cups</p>
            </div>
          </article>
        </section>
      </div>
    </main>
    <!-- footer -->
    <footer>
    <div class="footerContainer">
      <div class="footerNav">
        <li><%= link_to "Home", root_path%></li>
        <li><%= link_to "About Us", home_about_path%></li>
        <li><%= link_to "Meal Planner", meal_planner_index_path%></li>
      </div>
      <div class="footerBottom">
        <p>Created by <span class="designer">Zach Beesley</span></p>
      </div>
    </div>
    </footer>

    <script src="./js/app.js"></script>
  </body>
</html>



<div>
  <%= link_to "Edit", edit_recipe_path(@recipe), class:"btn btn-secondary" %> |
  <%= link_to "Back", recipes_path, class:"btn btn-secondary" %>
  <br/><br/>
  <%= button_to "Delete recipe", @recipe, method: :delete, class:"btn btn-outline-danger" %>
</div>