config/routes.rb
Rails.application.routes.draw do
  get "meals/index"
  get "less_than5_ingredients/index"
  get "less_than30_mins/index"
  get "desserts/index"
  get "snacks/index"
  get "breakfasts/index"
  get "meal_planner/index"
  resources :tags
  resources :steps
  resources :ingredients
  get "search", to: "search#index"
  devise_for :users
  resources :recipes
  #get "home/index"
  get 'home/about'
  root 'home#index'
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "/recipes/:id", to: "recipes#show"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
    @recipes = current_user.recipes
    @breakfasts = @recipes.where(dish_type: "Breakfast").order(:dish_name)
    @meals = @recipes.where(dish_type: "Meal").order(:dish_name)
    @desserts = @recipes.where(dish_type: "Dessert").order(:dish_name)
    @snacks = @recipes.where(dish_type: "Snack").order(:dish_name)
    @quick_foods = @recipes.where("prep_time + cook_time < 30").order(:dish_name)
    @easy_foods = @recipes.left_joins(:ingredients).group('recipes.id').having("COUNT(ingredients.id) < 5").order(:dish_name)

    else
      @breakfasts = Recipe.where(dish_type: "Nothing").order(:dish_name)
      @meals = Recipe.where(dish_type: "Nothing").order(:dish_name)
      @desserts = Recipe.where(dish_type: "Nothing").order(:dish_name)
      @snacks = Recipe.where(dish_type: "Nothing").order(:dish_name)
      @quick_foods = Recipe.where(dish_type: "Nothing").order(:dish_name)
      @easy_foods = Recipe.where(dish_type: "Nothing").order(:dish_name)    
    end
  end

  def about
    @recipes = Recipe.all
    @breakfasts = Recipe.where(dish_type: "Breakfast").order(:dish_name)
    @about_me = "My name is Zach" 
    @answer = 2 + 2
    puts "About action triggered"
    logger.debug "About action triggered"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<%= stylesheet_link_tag "https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css" %>
<%= javascript_include_tag "https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.bundle.min.js", defer: true %>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Recipes App", root_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <% link_to "About Us", home_about_path, class:"nav-link"%>
        </li>


        
        <% if user_signed_in? %>

          <li class="nav-item">
          <%= link_to "My Recipes", recipes_path, class:"nav-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "Add Recipe", new_recipe_path, class:"nav-link"%>
          </li>

          <li class="nav-item">
            <% link_to "Meal Planner", meal_planner_index_path, class:"nav-link"%>
          </li>
          
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete }, class:"nav-link", id:"sign-out-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link"%>
          </li>

          <li class="nav-item">
          <%= link_to "Search", search_path, class:"nav-link"%>
        </li>
      </ul>
      <%= form_with url: search_path, method: :get, class: "d-flex", role: "search" do %>
        <%= text_field_tag :q, nil, class: "form-control me-2", placeholder: "Search", aria: { label: "Search" } %>
        <%= submit_tag "Search", class: "btn btn-outline-success" %>
      <% end %>

        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link"%>
          </li>

          <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link"%>
          </li>
        

      <% end %>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<html>
  <body>

    <h1>Scroller</h1>
    
    <div class="scroller">
    <ul class="tag-list-scroller scroller__inner">
    <% @recipes.each do |recipe| %>
        <li><%= render recipe %></li>
    <% end %>
    </ul>
    </div>

  </body>
</html>

app/views/home/index.html.erb
<% content_for :title, "Recipes" %>
<% if user_signed_in? %>
<%= link_to "Breakfasts", breakfasts_index_path, class:"breakfast-index-header" %>

<div class="recipes" style="background: #50C878; border-radius: 30px; margin: 40px; padding: 20px;">
<% if @breakfasts.count > 6 %>
<div class="scroller">
<ul class="tag-list-scroller scroller__inner">
<% @breakfasts.each do |breakfast| %>
    <li><%= render breakfast %></li>
<% end %>
</ul>
</div>
</div>
</br>
</br>
<% else %>
<div style="display: inline-flex; flex-wrap: wrap;">
  <% @breakfasts.each do |breakfast| %>
    <%= render breakfast %>
  <% end %>
</div>
</div>
<br/>
<% end %>

<%= link_to "Meals", meals_index_path, class:"meal-index-header" %>

<div class="recipes" style="background: #FFBF00; border-radius: 30px; margin: 40px; padding: 20px;">
<% if @meals.count > 6 %>
<div class="scroller-reverse">
<ul class="tag-list-scroller scroller__inner-reverse">
<% @meals.each do |meal| %>
    <li><%= render meal %></li>
<% end %>
</ul>
</div>
</div>
<br/>
<% else %>
<div style="display: inline-flex; flex-wrap: wrap;">
  <% @meals.each do |meal| %>
    <%= render meal %>
  <% end %>
</div>
</div>
<br/>
<% end %>

<%= link_to "Desserts", desserts_index_path, class:"dessert-index-header" %>

<div class="recipes" style="background: #DE3163; border-radius: 30px; margin: 40px; padding: 20px;">
<% if @desserts.count > 6 %>
<div class="scroller">
<ul class="tag-list-scroller scroller__inner">
<% @desserts.each do |dessert| %>
    <li><%= render dessert %></li>
<% end %>
</ul>
</div>
</div>
<br/>
<% else %>
<div style="display: inline-flex;">
  <% @desserts.each do |dessert| %>
    <%= render dessert %>
  <% end %>
</div>
</div>
<br/>
<% end %>

<%= link_to "Snacks", snacks_index_path, class:"snack-index-header" %>

<div class="recipes" style="background: #6495ED; border-radius: 30px; margin: 40px; padding: 20px;">
<% if @snacks.count > 6 %>
<div class="scroller-reverse">
<ul class="tag-list-scroller scroller__inner-reverse">
<% @snacks.each do |snack| %>
    <li><%= render snack %></li>
<% end %>
</ul>
</div>
</div>
<br/>
<% else %>
<div style="display: inline-flex;">
  <% @snacks.each do |snack| %>
    <%= render snack %>
  <% end %>
</div>
</div>
<br/>
<% end %>

<%= link_to "Less Than 30 Mins", less_than30_mins_index_path, class:"quick-index-header" %>

<div class="recipes" style="background: #FA5F55; border-radius: 30px; margin: 40px; padding: 20px;">
<% if @quick_foods.count > 6 %>
<div class="scroller">
<ul class="tag-list-scroller scroller__inner">
<% @quick_foods.each do |food| %>
    <li><%= render food %></li>
<% end %>
</ul>
</div>
</div>
<br/>
<% else %>
<div style="display: inline-flex; flex-wrap: wrap;">
  <% @quick_foods.each do |food| %>
    <%= render food %>
  <% end %>
</div>
</div>
<br/>
<% end %>

<%= link_to "Less Than 5 Ingredients", less_than5_ingredients_index_path, class:"easy-index-header" %>

<div class="recipes" style="background: #CF9FFF; border-radius: 30px; margin: 40px; padding: 20px;">
<% if @easy_foods.count.keys.count > 6 %>
<div class="scroller-reverse">
<ul class="tag-list-scroller scroller__inner-reverse">
<% @easy_foods.each do |food| %>
    <li><%= render food %></li>
<% end %>
</ul>
</div>
</div>
<br/>
<% else %>
<div style="display: inline-flex; flex-wrap: wrap;">
  <% @easy_foods.each do |food| %>
    <%= render food %>
  <% end %>
</div>
</div>
<% end %>

<%= link_to "New recipe", new_recipe_path, class:"btn btn-secondary" %>

<% else %>
<h1>You need to sign in to view your recipes</h1>
<%= link_to "Sign Up", new_user_registration_path, class:"btn btn-secondary"%>

<%= link_to "Sign In", new_user_session_path, class:"btn btn-secondary"%>

<% end %>

app/views/home/meal_planner.html.erb
<table>
  <tr>
    <th>Company</th>
    <th>Contact</th>
    <th>Country</th>
  </tr>
  <tr>
    <% @recipes.each |each| %>
    <td>
    <a style="text-decoration:none" href=<%=ref%>>
    <div class="recipe-card">
            <figure>
              <%= image_tag(recipe.image)%>
            </figure>
          <div class="card-meta">
          <p class="dish-type-<%= recipe.dish_type%>" style="text-decoration:none" ><%= recipe.dish_type %></p>
          <ul class="dish-stats">
            <li>
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M8 2C4.6875 2 2 4.6875 2 8C2 11.3125 4.6875 14 8 14C11.3125 14 14 11.3125 14 8C14 4.6875 11.3125 2 8 2Z" stroke="#070705" stroke-opacity="0.25" stroke-miterlimit="10"/>
                <path d="M8 4V8.5H11" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
              <% total_time = (recipe.prep_time + recipe.cook_time) %>
                
              <%= total_time %> Mins.
            </li>
            <li>
              <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M4.9713 2.5C7.00005 2.5 8.00005 4.5 8.00005 4.5C8.00005 4.5 9.00005 2.5 11.0288 2.5C12.6775 2.5 13.9832 3.87937 14 5.52531C14.0344 8.94187 11.2897 11.3716 8.2813 13.4134C8.19836 13.4699 8.10036 13.5 8.00005 13.5C7.89973 13.5 7.80174 13.4699 7.7188 13.4134C4.71067 11.3716 1.96598 8.94187 2.00005 5.52531C2.01692 3.87937 3.32255 2.5 4.9713 2.5Z" stroke-linecap="round" stroke-linejoin="round"/>
              </svg>
                
              <%= recipe.number_of_likes %></h1>
            </li>
          </ul>
          </div>
          <h1><%= recipe.dish_name %></h1>
    </div>
    </a>
    </td>
    <% end %>
  </tr>
  <tr>
    <td>Centro comercial Moctezuma</td>
    <td>Francisco Chang</td>
    <td>Mexico</td>
  </tr>
</table>